services:
  bybit-bot:
    container_name: ${CONTAINER_NAME}
    image: ${COMPOSE_PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
        PROJECT_PATH: ${PROJECT_PATH}
        APP_DLL: ${APP_DLL}
    env_file:
      - .env
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      TZ: ${TZ}
      BYBIT_API_BASE_URL: ${BYBIT_API_BASE_URL}
      BYBIT_WS_PUBLIC_URL: ${BYBIT_WS_PUBLIC_URL}
      BYBIT_WS_PRIVATE_URL: ${BYBIT_WS_PRIVATE_URL}
      BYBIT_API_KEY: ${BYBIT_API_KEY}
      BYBIT_API_SECRET: ${BYBIT_API_SECRET}
      BYBIT_RECV_WINDOW: ${BYBIT_RECV_WINDOW}
      BYBIT_TESTNET: ${BYBIT_TESTNET}
      Logging__LogLevel__Default: ${LOG_LEVEL}
    restart: unless-stopped
